# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gPTZYofOXSTg_Kfxsql4eOLUmYy0ezCt
"""

!pip install yfinance xlrd

import pandas as pd

# Load the file you uploaded to Colab, assuming it's an HTML table
df_set = pd.read_html('/content/listedCompanies_en_US.xls', header=1)[0] # Use the second row (index 1) as the header
all_thai_tickers = [str(symbol).strip() + ".BK" for symbol in df_set['Symbol']]

"""### Fetching historical stock data for the last 15 days

I will now download daily stock data for all identified Thai tickers for the past 15 days using `yfinance`. This process can take some time due to the number of tickers. I will include a progress bar and basic error handling for tickers that might not have data available.
"""

import yfinance as yf
from datetime import datetime, timedelta
from tqdm.notebook import tqdm # For a progress bar

# Define the date range for the last 15 days
end_date = datetime.now()
start_date = end_date - timedelta(days=15)

print(f"Fetching data from {start_date.strftime('%Y-%m-%d')} to {end_date.strftime('%Y-%m-%d')}")

# Dictionary to store historical data
all_ticker_data = {}

# Fetch data for each ticker
for ticker_symbol in tqdm(all_thai_tickers, desc="Downloading data"):
    try:
        # Download daily data for the past 15 days
        data = yf.download(ticker_symbol, start=start_date, end=end_date, progress=False)
        if not data.empty:
            all_ticker_data[ticker_symbol] = data
    except Exception as e:
        # Print error for specific ticker but continue with others
        print(f"Error downloading data for {ticker_symbol}: {e}")

print(f"Successfully downloaded data for {len(all_ticker_data)} out of {len(all_thai_tickers)} tickers.")

"""### Identifying Top 20 "New Entry" by Volume

To identify "new entries" by volume, I will calculate the average daily trading volume for each stock over the last 15 days. The stocks with the highest average volumes will be considered the "top new entries" in terms of trading activity.
"""

import pandas as pd

# 1. Prepare lists to store volume data
historical_stats = []
today_stats = []

for ticker, df in all_ticker_data.items():
    if 'Volume' in df.columns and len(df) > 1:
        # yfinance returns multi-index columns; extract the specific ticker's volume column
        try:
            # Get the volume series for this ticker
            vols = df['Volume'][ticker].astype(float)

            # Historical period: all days except the most recent one
            avg_hist_vol = vols.iloc[:-1].mean()
            historical_stats.append({'Ticker': ticker, 'Avg_Hist_Volume': avg_hist_vol})

            # Today: the most recent day in the dataset
            today_vol = vols.iloc[-1]
            today_stats.append({'Ticker': ticker, 'Today_Volume': today_vol})
        except (KeyError, IndexError):
            continue

# 2. Determine the Top 20 Historical Volume Leaders
hist_df = pd.DataFrame(historical_stats)
top_20_hist_list = hist_df.sort_values(by='Avg_Hist_Volume', ascending=False).head(20)['Ticker'].tolist()

# 3. Determine Today's Top 20 Volume Leaders
today_df = pd.DataFrame(today_stats)
top_20_today_df = today_df.sort_values(by='Today_Volume', ascending=False).head(20)

# 4. Identify New Entries (In today's top 20, but NOT in historical top 20)
new_entries_df = top_20_today_df[~top_20_today_df['Ticker'].isin(top_20_hist_list)].copy()

# Add a column to show how much higher today's volume is compared to its own history
new_entries_df = new_entries_df.merge(hist_df, on='Ticker', how='left')
new_entries_df['Volume_Increase_Ratio'] = new_entries_df['Today_Volume'] / new_entries_df['Avg_Hist_Volume']

print("Today's Top 20 Volume Leaders:")
display(top_20_today_df.reset_index(drop=True))

print("\nNew Entries (Stocks in Today's Top 20 that were NOT in the Top 20 over the last 15 days):")
if not new_entries_df.empty:
    display(new_entries_df.sort_values(by='Today_Volume', ascending=False).reset_index(drop=True))
else:
    print("No new entries found today compared to the historical top list.")

def get_daily_new_entries(target_date, data_dict, window_days=15, top_n=20):
    """Identifies top volume stocks on target_date that weren't in the top list during the previous window."""
    hist_stats = []
    today_stats = []

    for ticker, df in data_dict.items():
        if 'Volume' not in df.columns:
            continue

        # Clean series for the specific ticker
        vols = df['Volume'][ticker].astype(float)

        # Get data before and on the target date
        past_data = vols[vols.index < target_date].tail(window_days)

        if target_date in vols.index and not past_data.empty:
            hist_stats.append({'Ticker': ticker, 'Avg_Hist_Vol': past_data.mean()})
            today_stats.append({'Ticker': ticker, 'Today_Vol': vols.loc[target_date]})

    if not today_stats or not hist_stats:
        return None

    # Top list from history
    hist_df = pd.DataFrame(hist_stats)
    top_hist_list = hist_df.sort_values(by='Avg_Hist_Vol', ascending=False).head(top_n)['Ticker'].tolist()

    # Top list today
    today_df = pd.DataFrame(today_stats)
    top_today_df = today_df.sort_values(by='Today_Vol', ascending=False).head(top_n)

    # Find new entries
    new_entries = top_today_df[~top_today_df['Ticker'].isin(top_hist_list)].copy()
    new_entries = new_entries.merge(hist_df, on='Ticker', how='left')
    new_entries['Ratio'] = new_entries['Today_Vol'] / new_entries['Avg_Hist_Vol']

    return new_entries.sort_values(by='Ratio', ascending=False)

# Get all unique trading dates from the dataset
all_dates = sorted(list(next(iter(all_ticker_data.values())).index))

print(f"Generating daily reports for {len(all_dates)} days...\n")

for d in all_dates:
    report = get_daily_new_entries(d, all_ticker_data)

    if report is not None and not report.empty:
        print(f"--- New Entries for {d.strftime('%Y-%m-%d')} ---")
        display(report.head(10).reset_index(drop=True)) # Show top 10 new entries by ratio
        print("\n")
    else:
        print(f"--- {d.strftime('%Y-%m-%d')}: No comparison data or no new entries ---\n")

daily_summary = []

for d in all_dates:
    report = get_daily_new_entries(d, all_ticker_data)
    if report is not None and not report.empty:
        # Get the top entry for this day by Ratio
        top_entry = report.iloc[0].to_dict()
        top_entry['Date'] = d.strftime('%Y-%m-%d')
        daily_summary.append(top_entry)

summary_df = pd.DataFrame(daily_summary)
print("Summary of the Top 'New Entry' for each day (Sorted by Date):")
display(summary_df[['Date', 'Ticker', 'Today_Vol', 'Avg_Hist_Vol', 'Ratio']])

import pandas as pd

# 1. Identify the two most recent dates
dates = sorted(list(next(iter(all_ticker_data.values())).index))
today = dates[-1]
yesterday = dates[-2]

def get_top_20_for_date(target_date, data_dict):
    stats = []
    for ticker, df in data_dict.items():
        if 'Volume' in df.columns and target_date in df.index:
            vol = float(df['Volume'][ticker].loc[target_date])
            stats.append({'Ticker': ticker, 'Volume': vol})
    return pd.DataFrame(stats).sort_values(by='Volume', ascending=False).head(20)

# 2. Get the lists
top_20_yesterday_df = get_top_20_for_date(yesterday, all_ticker_data)
top_20_today_df = get_top_20_for_date(today, all_ticker_data)

yesterday_list = top_20_yesterday_df['Ticker'].tolist()
today_list = top_20_today_df['Ticker'].tolist()

# 3. Find New Entries
new_stocks = [t for t in today_list if t not in yesterday_list]
new_stocks_df = top_20_today_df[top_20_today_df['Ticker'].isin(new_stocks)].copy()

print(f"Comparison: {yesterday.strftime('%Y-%m-%d')} vs {today.strftime('%Y-%m-%d')}")
print(f"\nNew stocks in Today's Top 20 that were NOT in Yesterday's Top 20:")
if new_stocks:
    display(new_stocks_df.reset_index(drop=True))
else:
    print("No new stocks found; the Top 20 list remains identical to yesterday.")

from collections import Counter

# 1. Track Top 20 appearances for all historical dates except today
historical_dates = dates[:-1]
appearance_counts = Counter()

for d in historical_dates:
    # Use the helper function created earlier
    daily_top_df = get_top_20_for_date(d, all_ticker_data)
    appearance_counts.update(daily_top_df['Ticker'].tolist())

# 2. Analyze Today's Top 20 relative to that history
today_top_df = get_top_20_for_date(today, all_ticker_data)

results = []
for ticker in today_top_df['Ticker']:
    count = appearance_counts.get(ticker, 0)
    results.append({
        'Ticker': ticker,
        'Today_Volume': today_top_df[today_top_df['Ticker'] == ticker]['Volume'].values[0],
        'Days_in_Top_20_Last_15_Days': count,
        'Status': 'NEW ENTRY' if count == 0 else 'RECURRING'
    })

# 3. Display Analysis
final_report_df = pd.DataFrame(results)

print(f"--- Analysis of Today's Top 20 ({today.strftime('%Y-%m-%d')}) ---")
print(f"Total historical trading days analyzed: {len(historical_dates)}\n")

display(final_report_df.sort_values(by=['Status', 'Today_Volume'], ascending=[True, False]).reset_index(drop=True))

# Ranking Today's Top 20 by Volume
today_ranked_df = today_top_df.sort_values(by='Volume', ascending=False).reset_index(drop=True)

print(f"Ranking of Today's Top 20 Volume Leaders ({today.strftime('%Y-%m-%d')}):")
display(today_ranked_df)

"""### Combined Report: New Entry Volume Leaders & Persistence

This report identifies stocks in today's Top 20 that are 'New Entries' (not in the Top 20 historical average) and shows their total frequency of appearance in the Top 20 over the last 15 trading days.
"""

import pandas as pd
from collections import Counter

# 1. Identify the reference dates
dates = sorted(list(next(iter(all_ticker_data.values())).index))
today = dates[-1]
historical_dates = dates[:-1]

# 2. Track Top 20 appearances over the last 15 days (including today)
appearance_counts = Counter()
for d in dates:
    daily_top = get_top_20_for_date(d, all_ticker_data)
    appearance_counts.update(daily_top['Ticker'].tolist())

# 3. Get Today's Top 20
today_top_df = get_top_20_for_date(today, all_ticker_data)

# 4. Get the Historical Top 20 List (based on 15-day average volume) for New Entry definition
hist_stats = []
for ticker, data in all_ticker_data.items():
    if 'Volume' in data.columns and len(data) > 1:
        vols = data['Volume'][ticker].astype(float)
        avg_vol = vols[vols.index < today].tail(15).mean()
        hist_stats.append({'Ticker': ticker, 'Avg_Hist_Vol': avg_vol})

top_20_hist_list = pd.DataFrame(hist_stats).sort_values(by='Avg_Hist_Vol', ascending=False).head(20)['Ticker'].tolist()

# 5. Build Combined Report
combined_results = []
for _, row in today_top_df.iterrows():
    ticker = row['Ticker']
    count = appearance_counts.get(ticker, 0)
    is_new_entry = ticker not in top_20_hist_list

    combined_results.append({
        'Ticker': ticker,
        'Today_Volume': row['Volume'],
        'Days_in_Top_20_Total': count,
        'Is_New_Entry': 'YES' if is_new_entry else 'NO'
    })

report_df = pd.DataFrame(combined_results)

print(f"--- Combined Volume Leader Report ({today.strftime('%Y-%m-%d')}) ---")
display(report_df.sort_values(by=['Is_New_Entry', 'Today_Volume'], ascending=[False, False]).reset_index(drop=True))

"""### Today's New Entry Highlights

Filtering the combined report to show only the stocks that are new to the volume leader list today.
"""

import pandas as pd

# Filter the report_df for only new entries
today_new_entries = report_df[report_df['Is_New_Entry'] == 'YES'].copy()

# Sort by volume to see the most active newcomers
today_new_entries = today_new_entries.sort_values(by='Today_Volume', ascending=False).reset_index(drop=True)

print(f"--- Stocks Identified as New Volume Leaders Today ({today.strftime('%Y-%m-%d')}) ---")
if not today_new_entries.empty:
    display(today_new_entries)
else:
    print("No stocks met the 'New Entry' criteria today.")

"""### True New Entries (Zero Previous Top 20 Appearances)

This report identifies stocks in today's Top 20 that have **never** appeared in the Top 20 list during the preceding historical window.
"""

import pandas as pd
from collections import Counter

# 1. Identify reference dates
dates = sorted(list(next(iter(all_ticker_data.values())).index))
today = dates[-1]
historical_dates = dates[:-1]

# 2. Count appearances in the Top 20 for HISTORICAL days ONLY
historical_appearance_counts = Counter()
for d in historical_dates:
    daily_top = get_top_20_for_date(d, all_ticker_data)
    historical_appearance_counts.update(daily_top['Ticker'].tolist())

# 3. Get Today's Top 20
today_top_df = get_top_20_for_date(today, all_ticker_data)

# 4. Filter for stocks with zero historical appearances
true_new_entries = []
for _, row in today_top_df.iterrows():
    ticker = row['Ticker']
    prev_count = historical_appearance_counts.get(ticker, 0)

    if prev_count == 0:
        true_new_entries.append({
            'Ticker': ticker,
            'Today_Volume': row['Volume'],
            'Previous_Appearances': 0
        })

true_new_df = pd.DataFrame(true_new_entries)

print(f"--- True New Entries Today ({today.strftime('%Y-%m-%d')}) ---")
print("(Stocks in Today's Top 20 with ZERO appearances in the Top 20 over the last 15 days)")

if not true_new_df.empty:
    display(true_new_df.sort_values(by='Today_Volume', ascending=False).reset_index(drop=True))
else:
    print("No stocks in today's Top 20 are completely new to the list.")

"""### Today's Top 20 Volume Ranking with Persistence and New Entry Flags

This report displays the top 20 stocks by volume for today, their total appearance count in the top list over the analysis period, and labels those with zero previous appearances.
"""

import pandas as pd
from collections import Counter

# 1. Identify dates
dates = sorted(list(next(iter(all_ticker_data.values())).index))
today = dates[-1]
historical_dates = dates[:-1]

# 2. Count appearances in Top 20 for HISTORICAL dates
hist_appearance_counts = Counter()
for d in historical_dates:
    daily_top = get_top_20_for_date(d, all_ticker_data)
    hist_appearance_counts.update(daily_top['Ticker'].tolist())

# 3. Get Today's Top 20
today_top_df = get_top_20_for_date(today, all_ticker_data)

# 4. Compile the final list with rankings and labels
final_ranking = []
for i, (_, row) in enumerate(today_top_df.iterrows(), 1):
    ticker = row['Ticker']
    prev_appearances = hist_appearance_counts.get(ticker, 0)

    final_ranking.append({
        'Rank': i,
        'Ticker': ticker,
        'Today_Volume': row['Volume'],
        'Prev_Appearances_15D': prev_appearances,
        'Entry_Status': 'NEW ENTRY' if prev_appearances == 0 else ''
    })

ranking_df = pd.DataFrame(final_ranking)

print(f"--- Top 20 Volume Ranking: {today.strftime('%Y-%m-%d')} ---")
display(ranking_df)

"""### Export Daily Report to Sheet (CSV)

This cell saves the latest Top 20 ranking to a CSV file called `daily_volume_report.csv`. You can find this file in the folder icon on the left sidebar in Colab.
"""

# Export to CSV for spreadsheet use
file_name = f"volume_report_{today.strftime('%Y_%m_%d')}.csv"
ranking_df.to_csv(file_name, index=False)

# Also save a generic 'latest' version
ranking_df.to_csv('latest_daily_volume_report.csv', index=False)

print(f"Success! Report saved as {file_name} and latest_daily_volume_report.csv")

"""### Sync to Google Sheets (Auto-Update Destination)
This cell will update a Google Sheet with today's report. Make sure you have created a sheet named 'Thai Stock Daily Report' or change the name in the code below.
"""

from google.colab import auth
import gspread
from google.auth import default

try:
    # Authenticate and create the gspread client
    auth.authenticate_user()
    creds, _ = default()
    gc = gspread.authorize(creds)

    # Change this to your actual Google Sheet name
    SHEET_NAME = 'Thai Stock Daily Report'

    try:
        sh = gc.open(SHEET_NAME)
    except gspread.SpreadsheetNotFound:
        sh = gc.create(SHEET_NAME)
        print(f"Created new sheet: {SHEET_NAME}")

    # Select the first worksheet
    worksheet = sh.get_worksheet(0)

    # Convert DataFrame to list of lists for gspread
    # Including headers
    values = [ranking_df.columns.values.tolist()] + ranking_df.values.tolist()

    # Clear existing and update using the non-deprecated argument order (values, range_name)
    worksheet.clear()
    worksheet.update(values, 'A1')
    print(f"Successfully updated Google Sheet: {sh.url}")

except Exception as e:
    print(f"Google Sheets Sync Error: {e}")
    print("Note: You must click the authentication link to allow the update.")

"""### 🔗 Live Report Link
Click the link below to view your automatically updated Google Sheet:
"""

print(f"Your live report is available here: https://docs.google.com/spreadsheets/d/1cHW5gfqlDxErkbz05A8pRtjhVD3nYKcnVOEPSD9XkKU")

"""### How to fully automate execution

To make this notebook run every day at a specific time without you clicking 'Run All':

1. **Colab Enterprise:** If you have access to Google Cloud Vertex AI, you can convert this notebook to a 'Scheduled Run'.
2. **Local Scheduler:** You can download this notebook as a `.py` script and use a local 'Cron Job' (Linux/Mac) or 'Task Scheduler' (Windows) if your computer stays on.
3. **GitHub Actions:** You can host the code on GitHub and use a 'Workflow' to run it on a schedule for free, though this requires moving the file handling to a cloud storage like S3 or GCS.

### GitHub Actions Automation Script

To use this, save your notebook as a Python script (`main.py`) and create a file at `.github/workflows/daily_run.yml` in your GitHub repository with the following content:

```yaml
name: Daily Thai Stock Update

on:
  schedule:
    - cron: '0 10 * * 1-5' # Runs at 10:00 UTC (5 PM BKK) Mon-Fri
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install yfinance pandas gspread google-auth tqdm lxml xlrd

      - name: Run Analysis
        env:
          # You would need to modify your code to read credentials from an ENV variable
          # instead of the interactive Google Colab auth
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: python main.py
```

### Interactive Data Sheet

Run the cell below to view the latest ranking in an interactive table format.
"""



from google.colab import data_table

# Enable interactive data table for a 'sheet' feel
data_table.enable_dataframe_formatter()

display(ranking_df)

"""### Simplified 'New Entry' Tracking (Rank-Based Only)
This logic identifies stocks in today's Top 20 that did not appear in the Top 20 at all during the previous 15 trading days. It ignores averages and volume spikes.
"""

import pandas as pd
from collections import Counter

# 1. Identify reference dates
dates = sorted(list(next(iter(all_ticker_data.values())).index))
today = dates[-1]
historical_dates = dates[:-1]

# 2. Track Top 20 appearances for all historical days
hist_appearance_counts = Counter()
for d in historical_dates:
    daily_top = get_top_20_for_date(d, all_ticker_data)
    hist_appearance_counts.update(daily_top['Ticker'].tolist())

# 3. Find unique members of historical Top 20s for 'New Entry' flag
hist_top_20_members = set(hist_appearance_counts.keys())

# 4. Get Today's Top 20
today_top_df = get_top_20_for_date(today, all_ticker_data)

# 5. Build report with appearance frequency
final_results = []
for i, (_, row) in enumerate(today_top_df.iterrows(), 1):
    ticker = row['Ticker']
    was_in_history = ticker in hist_top_20_members
    freq = hist_appearance_counts.get(ticker, 0)

    final_results.append({
        'Rank': i,
        'Ticker': ticker,
        'Today_Volume': row['Volume'],
        'Appearances_Last_15D': freq,
        'Status': 'NEW ENTRY' if not was_in_history else 'RECURRING'
    })

simplified_report_df = pd.DataFrame(final_results)

print(f"--- Daily Rank & Persistence Report ({today.strftime('%Y-%m-%d')}) ---")
display(simplified_report_df)

"""### Value-Based Analysis (Price × Volume)
This section calculates the trading value for each stock to identify the Top 20 by liquidity in terms of Baht, rather than just share count.
"""

import pandas as pd

# 1. Calculate Daily Trading Value (Close Price * Volume) for today
# This identifies stocks with the most money flowing through them today
value_stats = []
for ticker, df in all_ticker_data.items():
    if today in df.index:
        try:
            # Access the underlying data series to avoid multi-index errors
            price = float(df['Close'][ticker].loc[today])
            vol = float(df['Volume'][ticker].loc[today])
            trading_value = price * vol

            if trading_value > 0:
                value_stats.append({
                    'Ticker': ticker,
                    'Price': round(price, 2),
                    'Volume': int(vol),
                    'Trading_Value_Baht': round(trading_value, 2)
                })
        except (KeyError, ValueError, TypeError):
            continue

# 2. Rank by Trading Value (Top 20)
value_ranking_df = pd.DataFrame(value_stats)
value_ranking_df = value_ranking_df.sort_values(by='Trading_Value_Baht', ascending=False).head(20).reset_index(drop=True)
value_ranking_df.insert(0, 'Rank', range(1, len(value_ranking_df) + 1))

print(f"--- Top 20 Stocks by Daily Trading Value ({today.strftime('%Y-%m-%d')}) ---")
display(value_ranking_df)

"""### Update Google Sheets: Value Analysis Sheet"""

try:
    sh = gc.open(SHEET_NAME)

    # Sync to 'Value Analysis' tab
    try:
        ws_value = sh.worksheet('Value Analysis')
    except gspread.WorksheetNotFound:
        ws_value = sh.add_worksheet(title='Value Analysis', rows="100", cols="20")

    # Convert DataFrame to list format for gspread
    value_export = [value_ranking_df.columns.values.tolist()] + value_ranking_df.values.tolist()

    ws_value.clear()
    ws_value.update(value_export, 'A1')
    print(f"Successfully updated 'Value Analysis' tab with Trading Value data: {sh.url}")

except Exception as e:
    print(f"Error syncing value data: {e}")

"""### Value-Based New Entry & Persistence Analysis
This logic identifies stocks in today's Top 20 by **Trading Value** that did not appear in the Top 20 by value during the previous 15 trading days.
"""

import pandas as pd
from collections import Counter

def get_top_20_value_for_date(target_date, data_dict):
    stats = []
    for ticker, df in data_dict.items():
        if all(col in df.columns for col in ['Close', 'Volume']) and target_date in df.index:
            try:
                price = float(df['Close'][ticker].loc[target_date])
                vol = float(df['Volume'][ticker].loc[target_date])
                stats.append({'Ticker': ticker, 'Value': price * vol})
            except (KeyError, ValueError): continue
    return pd.DataFrame(stats).sort_values(by='Value', ascending=False).head(20)

# 1. Track Top 20 Value appearances for historical days
hist_value_counts = Counter()
for d in historical_dates:
    daily_top_val = get_top_20_value_for_date(d, all_ticker_data)
    hist_value_counts.update(daily_top_val['Ticker'].tolist())

# 2. Get Today's Top 20 Value
today_top_value_df = get_top_20_value_for_date(today, all_ticker_data)

# 3. Build report
value_persistence = []
for i, (_, row) in enumerate(today_top_value_df.iterrows(), 1):
    ticker = row['Ticker']
    prev_freq = hist_value_counts.get(ticker, 0)
    value_persistence.append({
        'Rank': i,
        'Ticker': ticker,
        'Today_Value_Baht': row['Value'],
        'Prev_Appearances_Value_15D': prev_freq,
        'Entry_Status': 'NEW VALUE ENTRY' if prev_freq == 0 else ''
    })

value_persistence_df = pd.DataFrame(value_persistence)
print(f"--- Value-Based Rank & Persistence Report ({today.strftime('%Y-%m-%d')}) ---")
display(value_persistence_df)

"""### Update Google Sheets: Value Persistence"""

try:
    sh = gc.open(SHEET_NAME)
    # We'll put this detailed report in a dedicated sheet
    try:
        ws_val_persist = sh.worksheet('Value Persistence')
    except gspread.WorksheetNotFound:
        ws_val_persist = sh.add_worksheet(title='Value Persistence', rows="100", cols="20")

    val_persist_values = [value_persistence_df.columns.values.tolist()] + value_persistence_df.values.tolist()
    ws_val_persist.clear()
    ws_val_persist.update(val_persist_values, 'A1')
    print(f"Successfully updated 'Value Persistence' sheet in: {sh.url}")
except Exception as e:
    print(f"Error: {e}")

